# Generated by Django 4.1.1 on 2022-11-06 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_curriculumfiles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curriculumfiles',
            name='excelFile',
            field=models.BinaryField(),
        ),
    ]
