# Generated by Django 4.1.1 on 2022-11-06 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_delete_curriculumfiles'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurriculumFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.TextField()),
                ('excelFile', models.BinaryField()),
            ],
        ),
    ]
